import Head from "next/head";
import Sidebar from "@/components/Sidebar";
import HomeSection from "@/components/HomeSection";
import AboutSection from "@/components/AboutSection";
import classes from "../styles/homePage.module.css"
import SkillsSection from "@/components/SkillsSection";
import ProjectsSection from "@/components/ProjectsSection";
import TalkSection from "@/components/TalkSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Yousef Ahmed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className="row m-0">
          <Sidebar />
          <div className={`col-9 ${classes.rightDiv}`}>
            <HomeSection />
            <AboutSection />
            <SkillsSection/>
            <ProjectsSection/>
            <TalkSection/>
          </div>
        </div>
      </main>
    </>
  );
}
